### ISSUE TITLE
autobuild nox image on new release

### ISSUE THREAD

**Issue by TheKevJames** [TheKevJames/tools#2]
Figure out a way to either:
- at best: build and tag a new version of [thekevjames/nox](https://cloud.docker.com/repository/docker/thekevjames/nox/general) whenever there's a new [nox](https://pypi.org/project/nox/) release, or
- at least: send an alert / set a failure tag / etc on each [nox](https://pypi.org/project/nox/) release

**Comment by TheKevJames** [comment]
In a shocking display of low-tech automation, I've subscribed to release notifications on the upstream repo and am using myself as a webhook. It would still be great to work on a bit more in the way of automation.

**Comment by nilsdebruin** [comment]
Hi Kevin!

I am happily making use of your Nox Docker build and read this issue! I am also still searching for something similar you are describing; creating automated builds when versions change including tagging. That would be really awesome! In case I find something useful I will let you know!

**Comment by seanblumenfeld** [comment]
Hi @TheKevJames,

Thanks for putting together this nox Dockerfile. I have used it in a project.

I have cloned your repo and put together a relatively simple way of automating the nox version upgrade and opened a [pull request](https://github.com/TheKevJames/tools/pull/280) for you.

Let me know what you think or if it needs any tweaks.

Cheers!
Sean

**Comment by TheKevJames** [comment]
Solved via [autobuilding on master, tagging the image based on parsing the requirements file](https://github.com/TheKevJames/tools/commit/87ad6d872edde6ecb04c160725ba9688d398a7bb) and then [having renovate autoupdate the requirements file](https://github.com/TheKevJames/tools/commit/4dc3de14c0c103e29cfc36674527fb38229d237f)
