### ISSUE TITLE
mysql-tuner / perl error message: diagnostics

### ISSUE THREAD

**Issue by jonasjonas** [TheKevJames/tools#21]
Hi, thanks for providing the mysql-tuner docker file.

At the moment I am unable to run it, because its seems that some perl dependency is missing:

```
couldn't find diagnostic data in /usr/share/perl5/core_perl/pods/perldiag.pod /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl /mysqltuner.pl at /usr/share/perl5/core_perl/diagnostics.pm line 259, <POD_DIAG> line 711.
Compilation failed in require at /mysqltuner.pl line 45.
BEGIN failed--compilation aborted at /mysqltuner.pl line 45.
```

All I could find was, that the perl installation would be incomplete. But reinstalling perl did not seem to help.

Maybe it is a problem with the latest alpine version?

**Comment by jonasjonas** [comment]
Ah, too early:
It seems, that there is a dependency missing.

If one add `perl-doc` it works again.

```
apk --update add mysql-client perl perl-doc
```

**Comment by TheKevJames** [comment]
@jonasjonas sorry for the late reply on this -- looks like I didn't have notifications enabled for this repo.

Thanks for the issue report and for finding the solution here! I've just pushed a changeset for adding `perldoc` (23a59b520f3b90ceec2b4a61757b16ee8d77cec4) which should be live on Dockerhub shortly. Please let me know if you continue to have issues!
