### ISSUE TITLE
Update the minify container

### ISSUE THREAD

**Issue by Simonmicro** [TheKevJames/tools#48]
The release 2.9.3 is broken (https://github.com/tdewolff/minify/issues/326) - I would love if you could add an other version tag to Docker Hub (and update it of course).

**Thank you very much!**

**Comment by TheKevJames** [comment]
And done -- should be live as soon as the DockerHub build finishes (normally in the 5-10m range). Thanks for the ping -- I'd completely missed the 2.9.4 release!

**Comment by Simonmicro** [comment]
Thanks! :+1: 

_You may have forgotten to update the latest tag..._

**Comment by TheKevJames** [comment]
Thanks -- completely slipped my mind that `:latest` was only linked to commits, not just tags. Fixing...
